### PR TITLE
Add External Interface

### PR DESCRIPTION
**Pull request by SirDiazo**
Do not merge yet, not fully tested.

I'm asking for feedback on this if this approach would work for you to add to IR-Sequencer.

This adds an external interface for other mods to start/stop sequences. I was asked for the functionality to start/stop sequences via the action group system and this gives me the ability to do so. 

All the controlling logic for the action group system is in my mod, this PR is just exposing methods to start/stop/reset sequences.

### CODE REVIEW

**Comment by ZiwKerman** [comment]
I don't mind this, but you should add more null checking. Instance.sequences may be null for a craft with no sequences and even Instance itself may be null for non-IR aware craft or if IR API failed to load. 

Also please note, that if sequence user is about to start employs any servos, that are already used in other running sequences then it would fail to start and because user does it outside of UI he might not get the error message.

**Comment by ZiwKerman** [comment]
Some more thoughts:

1) I've been thinking on adding some unique IDs to sequences, but there was no need for that so far. But if it helps, I can start working on that in the next release

2) If you plan to add a list of sequences to AGX UI don't forget to null-check both Instance and Instance.sequences

**Comment by SirDiazo** [comment]
Yes, more error-trapping/null checking is needed. I just threw this together to make sure you would be okay with it before I sink a bunch of time into this.

However, I think you are thinking a bit more ambitious then what I'm actually planning. I simply intend to implement an action that can start/stop/reset a sequence, I'm not looking to list the sequences or anything like that in my own mod.

The unique IDs thing is interesting however, the big weakness of my current approach is that it is based on the order of sequences as visible in the Sequence Manager. If they have 3 sequences (A, B, C) and create the StartSequence2 action, it will start sequence B. However, if they delete sequence A, StartSequence2 will now start sequence C because that is now the second sequence in the list.

I did consider using the sequence name, but that is not guaranteed unique.

If you do add a unique ID, would it be player visible? Right now the way the player identifies which sequence the action is controlling by typing in the number of the sequence in a text box which doesn't update when the order of sequences changes.

I'm not sure how to approach this part yet, this is intended to be part of ModActions rather then AGX and it already has a GUI setup laid out.

http://forum.kerbalspaceprogram.com/index.php?/topic/116142-105jul1615-modactions-control-your-vessel-including-other-mods-via-actiongroups

Shows the interface I currently have.

**Comment by ZiwKerman** [comment]
I do not plan to make the ID visible anywhere in the UI for now. But for your purposes I'd suggest switch to sequence names, but add some visual message if user tries to call a non-unique sequence or non-existing sequence.

**Comment by ZiwKerman** [comment]
If the user is too lazy to name their sequences, then he is beyond help :)

**Comment by SirDiazo** [comment]
Very true.

Alright, I'll see if I can get something up and running this weekend.

Closing this PR as it should not be merged.

**Pull request closed without merging**
